# Generated by Django 2.1.5 on 2019-01-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0010_auto_20190109_0956'),
        ('mis', '0001_initial'),
        ('callcard', '0004_callrecord_mis_call_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterLogic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'FilterLogic',
                'verbose_name_plural': 'FilterLogic',
            },
        ),
        migrations.CreateModel(
            name='PushCustomer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Push Customer',
                'verbose_name_plural': 'Push Customers',
            },
        ),
        migrations.CreateModel(
            name='PushFilter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Filter name')),
                ('push_url', models.URLField(null=True)),
                ('chief_complain_text', models.CharField(blank=True, max_length=64, null=True)),
                ('address_district', models.CharField(blank=True, max_length=64, null=True)),
                ('address_city', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address_city_logic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_city_logic', to='pushapi.FilterLogic')),
                ('address_district_logic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_district_logic', to='pushapi.FilterLogic')),
                ('address_locationtype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mis.LocationType')),
                ('address_locationtype_logic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_locationtype_logic', to='pushapi.FilterLogic')),
                ('call_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callcard.CallPriority')),
                ('call_priority_logic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='call_priority_logic', to='pushapi.FilterLogic')),
                ('call_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callcard.CallResult')),
                ('call_result_logic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='call_result_logic', to='pushapi.FilterLogic')),
                ('call_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callcard.CallStations')),
                ('call_station_logic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='call_station_logic', to='pushapi.FilterLogic')),
                ('chief_complain_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.ChiefComplain')),
                ('complain_code_logic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complain_logic_code', to='pushapi.FilterLogic')),
                ('complain_text_logic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complain_logic_text', to='pushapi.FilterLogic')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushapi.PushCustomer')),
                ('mis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis')),
                ('mis_id_logic', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='mis_id_logic', to='pushapi.FilterLogic')),
            ],
            options={
                'verbose_name': 'Push Filter',
                'verbose_name_plural': 'Push Filters',
            },
        ),
        migrations.CreateModel(
            name='PushQueue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('push_url', models.URLField(null=True)),
                ('message', models.CharField(max_length=1024, null=True)),
                ('date_sent', models.DateTimeField(null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcard.CallCard')),
                ('push_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushapi.PushFilter')),
            ],
            options={
                'verbose_name': 'Push Queue',
                'verbose_name_plural': 'Push Queue',
            },
        ),
        migrations.CreateModel(
            name='PushStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Push Queue Status',
                'verbose_name_plural': 'Push Queue Statuses',
            },
        ),
        migrations.AddField(
            model_name='pushqueue',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pushapi.PushStatus'),
        ),
    ]
