# Generated by Django 2.1.5 on 2019-04-17 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=64)),
                ('chanel', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TelegramBot',
                'verbose_name_plural': 'TelegramBots',
            },
        ),
        migrations.AddField(
            model_name='pushfilter',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pushfilter',
            name='is_push_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pushfilter',
            name='telegram_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pushapi.TelegramBot'),
        ),
        migrations.AddField(
            model_name='pushqueue',
            name='telegram_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pushapi.TelegramBot'),
        ),
    ]
