# Generated by Django 2.1.3 on 2018-11-28 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('mis', '0001_initial'),
        ('crew', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('call_card_id', models.CharField(max_length=32, unique=True)),
                ('mis_call_card_id', models.CharField(max_length=64)),
                ('caller_number', models.CharField(max_length=64, null=True)),
                ('call_comment', models.CharField(max_length=255, null=True)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Address')),
            ],
        ),
        migrations.CreateModel(
            name='CallCardSlug',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallPriority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_name', models.CharField(max_length=32)),
                ('priority_comment', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('call_record_seq', models.IntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('call_record_comment', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_name', models.CharField(max_length=32)),
                ('result_comment', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallStations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=32)),
                ('station_comment', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='callrecord',
            name='call_station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='callcard.CallStations'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='card_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='callcard.CallCard'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='crew_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew.Crew'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='mis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='operator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Staff'),
        ),
        migrations.AddField(
            model_name='callcard',
            name='call_priority',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='callcard.CallPriority'),
        ),
        migrations.AddField(
            model_name='callcard',
            name='call_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='callcard.CallResult'),
        ),
        migrations.AddField(
            model_name='callcard',
            name='call_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcard.CallStations'),
        ),
        migrations.AddField(
            model_name='callcard',
            name='complain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Complain'),
        ),
        migrations.AddField(
            model_name='callcard',
            name='crew_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew.Crew'),
        ),
        migrations.AddField(
            model_name='callcard',
            name='mis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis'),
        ),
        migrations.AddField(
            model_name='callcard',
            name='mis_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callcard',
            name='operator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Staff'),
        ),
        migrations.AddField(
            model_name='callcard',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Patient'),
        ),
    ]
