# Generated by Django 2.1.3 on 2018-12-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcard',
            name='call_card_id',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
