# Generated by Django 2.1.3 on 2018-12-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcard', '0002_auto_20181204_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcard.CallCard'),
        ),
    ]
