# Generated by Django 2.1.3 on 2018-12-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcard', '0003_auto_20181204_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='mis_call_card_id',
            field=models.CharField(default='15', max_length=64),
            preserve_default=False,
        ),
    ]
