# Generated by Django 2.1.5 on 2019-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcard', '0004_callrecord_mis_call_card_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callcard',
            index=models.Index(fields=['timestamp'], name='callcard_ca_timesta_d8037c_idx'),
        ),
        migrations.AddIndex(
            model_name='callcard',
            index=models.Index(fields=['start_datetime'], name='callcard_ca_start_d_98a29d_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['start_datetime'], name='callcard_ca_start_d_459419_idx'),
        ),
    ]
