# Generated by Django 2.2.1 on 2019-05-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcard', '0006_auto_20190322_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcard',
            name='call_priority',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='callcard.CallPriority'),
        ),
    ]
