# Generated by Django 2.1.5 on 2019-03-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qarobot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytest',
            old_name='er_with_arrival',
            new_name='active_crew',
        ),
    ]
