# Generated by Django 2.1.5 on 2019-04-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarobot', '0002_auto_20190305_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytest',
            name='email',
            field=models.EmailField(default='central103@central103.org', max_length=254),
        ),
    ]
