# Generated by Django 2.2.1 on 2019-05-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qarobot', '0003_dailytest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytest',
            name='steel_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailytest',
            name='mis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis'),
        ),
    ]
