# Generated by Django 2.1.3 on 2018-11-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcard', '0001_initial'),
        ('crew', '0004_crewdairy_call_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewdairy',
            name='call_station',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='callcard.CallStations'),
            preserve_default=False,
        ),
    ]
