# Generated by Django 2.1.3 on 2018-12-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0005_crewdairy_call_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_id',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
