# Generated by Django 2.1.5 on 2019-03-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0006_auto_20181204_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mis.Cars'),
        ),
    ]
