# Generated by Django 2.1.5 on 2019-03-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0007_auto_20190311_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='crew_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
