# Generated by Django 2.1.3 on 2018-11-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mis', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mis_heartbeat', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('mis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis')),
            ],
        ),
        migrations.CreateModel(
            name='Intercall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mis_to', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Address')),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Complain')),
                ('mis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
