# Generated by Django 2.1.5 on 2019-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['timestamp'], name='heartbeat_h_timesta_785c48_idx'),
        ),
    ]
