# Generated by Django 2.1.5 on 2019-03-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0002_auto_20190209_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercall',
            name='address',
        ),
        migrations.RemoveField(
            model_name='intercall',
            name='complain',
        ),
        migrations.RemoveField(
            model_name='intercall',
            name='mis_id',
        ),
        migrations.RemoveField(
            model_name='intercall',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Intercall',
        ),
    ]
