# Generated by Django 2.1.5 on 2019-03-29 07:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0004_auto_20190329_0646'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='intercallq',
            managers=[
                ('line', django.db.models.manager.Manager()),
            ],
        ),
    ]
