# Generated by Django 2.1.5 on 2019-03-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0005_auto_20190329_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intercallq',
            old_name='Intercall',
            new_name='intercall',
        ),
    ]
