# Generated by Django 2.1.5 on 2019-03-29 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0006_auto_20190329_0753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntercallQSatus',
            new_name='IntercallSatus',
        ),
        migrations.RemoveField(
            model_name='intercallq',
            name='intercall',
        ),
        migrations.RemoveField(
            model_name='intercallq',
            name='status',
        ),
        migrations.AddField(
            model_name='intercall',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heartbeat.IntercallSatus'),
        ),
        migrations.DeleteModel(
            name='IntercallQ',
        ),
    ]
