# Generated by Django 2.1.3 on 2018-11-28 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('addresstype_name', models.CharField(max_length=64)),
                ('addresstype_short', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('carowner_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mis_car_id', models.CharField(max_length=32)),
                ('mis_facility_id', models.CharField(max_length=16)),
                ('car_model', models.CharField(max_length=64, null=True)),
                ('year_made', models.IntegerField(default=1980)),
                ('year_start', models.IntegerField(default=1980)),
                ('gov_number', models.CharField(max_length=16, null=True)),
                ('car_field_number', models.CharField(max_length=16, null=True)),
                ('car_comment', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.CarOwner')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('carstatus_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cartype_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mis_facility_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('facility_contact', models.CharField(max_length=255, null=True)),
                ('facility_phone', models.CharField(max_length=32, null=True)),
                ('facility_comment', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('facility_parent', models.CharField(default='0', max_length=16)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('facilitytype_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('locationtype_name', models.CharField(max_length=64)),
                ('locationtype_short', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Mis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mis_type', models.CharField(default='M', max_length=1)),
                ('mis_name', models.CharField(default='Невідома МІС', max_length=255)),
                ('mis_facility', models.IntegerField(default=0)),
                ('mis_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accept_intercall', models.BooleanField(default=True)),
                ('mis_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mis_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mis',
                'verbose_name_plural': 'Mis',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mis_staff_id', models.CharField(max_length=32)),
                ('mis_facility_id', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=64)),
                ('family_name', models.CharField(blank=True, max_length=64, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('experience_total', models.CharField(max_length=16, null=True)),
                ('experience_field', models.CharField(max_length=16, null=True)),
                ('ipn', models.CharField(max_length=16, null=True)),
                ('passport', models.CharField(max_length=32, null=True)),
                ('sertificate', models.CharField(max_length=32, null=True)),
                ('last_qualification_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Facility')),
                ('mis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qualification_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTitle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SysAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.CharField(max_length=5, null=True)),
                ('district', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('apartment', models.CharField(max_length=16, null=True)),
                ('longitude', models.CharField(max_length=64, null=True)),
                ('latitude', models.CharField(max_length=64, null=True)),
                ('address_comment', models.CharField(max_length=255, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.AddressType')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.LocationType')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.StaffQualification'),
        ),
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.StaffTitle'),
        ),
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.SysAddress'),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.FacilityType'),
        ),
        migrations.AddField(
            model_name='facility',
            name='mis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.CarStatus'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.CarType'),
        ),
        migrations.AddField(
            model_name='cars',
            name='facility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Facility'),
        ),
        migrations.AddField(
            model_name='cars',
            name='mis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('mis_id', 'mis_staff_id')},
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('mis_id', 'mis_facility_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cars',
            unique_together={('mis_id', 'mis_car_id')},
        ),
    ]
