# Generated by Django 2.1.5 on 2019-01-31 14:23

from django.db import migrations, models
import django.db.models.deletion


def populate_mistype(apps, schema_editor):
    MisType = apps.get_model("mis", "MisType")
    MisType.objects.create(mistype_name='MIS', mistype_comment='Real MIS')
    MisType.objects.create(mistype_name='Extension', mistype_comment='MIS Extension')
    MisType.objects.create(mistype_name='Test', mistype_comment='For Test purpose')
    MisType.objects.create(mistype_name='Waiting', mistype_comment='Not connected')


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mistype_name', models.CharField(max_length=16)),
                ('mistype_comment', models.CharField(max_length=32)),
            ],
        ),
        migrations.RunPython(populate_mistype),
        migrations.RemoveField(
            model_name='mis',
            name='mis_type',
        ),
        migrations.AddField(
            model_name='mis',
            name='mis_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mis.MisType'),
        ),
    ]
