# Generated by Django 2.2.2 on 2019-06-29 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20190629_1913'),
        ('mis', '0002_mistype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mis',
            name='state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.State'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_field_number',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mis',
            name='mis_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
