# Generated by Django 2.1.3 on 2018-12-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_complain_complain4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(default='30р.', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='Не відомо', max_length=16),
            preserve_default=False,
        ),
    ]
