# Generated by Django 2.1.3 on 2019-01-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20181218_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='code_complain',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='code_sit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
