# Generated by Django 2.1.3 on 2019-01-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20190102_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ChiefComplain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complain_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConscState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PatientState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_code', models.IntegerField()),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('chief_complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.ChiefComplain')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_dsns', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='complain',
            name='code_sit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Situation'),
        ),
        migrations.AddField(
            model_name='complain',
            name='breath_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.BreathState'),
        ),
        migrations.AddField(
            model_name='complain',
            name='chief_complain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.ChiefComplain'),
        ),
        migrations.AddField(
            model_name='complain',
            name='consc_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.ConscState'),
        ),
        migrations.AddField(
            model_name='complain',
            name='patient_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.PatientState'),
        ),
    ]
