# Generated by Django 2.1.3 on 2019-01-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20190106_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chiefcomplain',
            old_name='complain_name',
            new_name='name',
        ),
    ]
