# Generated by Django 2.1.5 on 2019-05-01 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0010_auto_20190109_0956'),
        ('callcard', '0006_auto_20190322_1940'),
        ('mis', '0002_mistype'),
        ('crew', '0008_crew_crew_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddrDocType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MedRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('med_record_id', models.SlugField(max_length=32, unique=True)),
                ('call_card_id', models.SlugField(max_length=32)),
                ('mis_medrecord_id', models.CharField(max_length=64)),
                ('start_datetime', models.DateTimeField()),
                ('time_crew', models.DateTimeField()),
                ('time_depart', models.DateTimeField()),
                ('time_patient', models.DateTimeField(null=True)),
                ('time_transport', models.DateTimeField(null=True)),
                ('time_hospital', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField()),
                ('patient_document', models.CharField(blank=True, max_length=64, null=True)),
                ('primary_exam', models.CharField(max_length=64, null=True)),
                ('secondary_exam', models.CharField(max_length=64, null=True)),
                ('medical_history', models.CharField(blank=True, max_length=1024, null=True)),
                ('therapy_materials', models.CharField(blank=True, max_length=1024, null=True)),
                ('alergy', models.CharField(blank=True, max_length=1024, null=True)),
                ('help_privided', models.CharField(blank=True, max_length=256, null=True)),
                ('reanimation', models.CharField(blank=True, max_length=256, null=True)),
                ('medicine_applyed', models.BooleanField(default=False)),
                ('is_hospital_record', models.BooleanField(default=False)),
                ('is_diagnosis_record', models.BooleanField(default=False)),
                ('mr_comment', models.CharField(max_length=255, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_address_medrecord', to='patients.Address')),
                ('callcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcard.CallCard')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Crew')),
                ('mis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Mis')),
            ],
            options={
                'verbose_name': 'MedRecord',
                'verbose_name_plural': 'MedRecords',
            },
        ),
        migrations.CreateModel(
            name='MedRecordSlug',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MKX',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code3_code', models.CharField(max_length=4)),
                ('code_full', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=256)),
                ('code_big', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MKXcode1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('code_start', models.CharField(max_length=8)),
                ('code_end', models.CharField(max_length=8)),
                ('code_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MKXcode2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('code_start', models.CharField(max_length=8)),
                ('code_end', models.CharField(max_length=8)),
                ('code_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MKXcode3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('code_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MRDiagnosis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('diagnosis_seq', models.IntegerField()),
                ('med_record_id', models.SlugField(max_length=32)),
                ('d_text', models.CharField(max_length=256, null=True)),
                ('is_crew', models.BooleanField(default=True)),
                ('doctor_name', models.CharField(max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('callcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcard.CallCard')),
                ('medrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medrecord.MedRecord')),
                ('mkx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medrecord.MKX')),
            ],
        ),
        migrations.CreateModel(
            name='MRHospital',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hospital_seq', models.IntegerField()),
                ('med_record_id', models.SlugField(max_length=32)),
                ('the_place', models.CharField(max_length=255)),
                ('the_doctor', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=32, null=True)),
                ('event_datetime', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('callcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcard.CallCard')),
                ('medrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medrecord.MedRecord')),
            ],
        ),
        migrations.CreateModel(
            name='MRResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('death_datetime', models.DateTimeField(null=True)),
                ('is_hospital', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ResultAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TheResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='mrresult',
            name='result_action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medrecord.ResultAction'),
        ),
        migrations.AddField(
            model_name='mrresult',
            name='the_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medrecord.TheResult'),
        ),
        migrations.AddField(
            model_name='mkx',
            name='code1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medrecord.MKXcode1'),
        ),
        migrations.AddField(
            model_name='mkx',
            name='code2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medrecord.MKXcode2'),
        ),
        migrations.AddField(
            model_name='mkx',
            name='code3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medrecord.MKXcode3'),
        ),
        migrations.AddField(
            model_name='medrecord',
            name='mr_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medrecord.MRResult'),
        ),
        migrations.AddField(
            model_name='medrecord',
            name='noresult',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medrecord.NoResult'),
        ),
        migrations.AddField(
            model_name='medrecord',
            name='operator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Staff'),
        ),
        migrations.AddField(
            model_name='medrecord',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='medrecord',
            name='patient_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_address_medrecord', to='patients.Address'),
        ),
        migrations.AddField(
            model_name='medrecord',
            name='patient_address_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medrecord.AddrDocType'),
        ),
    ]
