# Generated by Django 2.1.5 on 2019-05-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecord',
            name='call_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_address_medrecord', to='patients.Address'),
        ),
        migrations.AlterField(
            model_name='medrecord',
            name='mr_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medrecord.MRResult'),
        ),
        migrations.AlterField(
            model_name='medrecord',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='medrecord',
            name='patient_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_address_medrecord', to='patients.Address'),
        ),
        migrations.AlterField(
            model_name='mrdiagnosis',
            name='mkx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medrecord.MKX'),
        ),
    ]
